language: node_js
sudo: false
node_js: 'node'
branches:
  except:
    - releases
    - gh-pages
before_deploy: bash ./ci/build_release.sh
deploy:
- provider: releases
  api_key:
    secure: cDVJluCReiLGADQ4MwLMzKTM5vtioImeKlJx9P42clu4hjKR89zylNQyUQwTtao0h64zX+QfpKUhwTIhNHz58oDVqk6r6g2omy9+mtEHHVfHXdnYqQI0b9lU4Yllcc51sa8CpYH5CYImFdxwpduOkK7M7M/1ozwJitVHIlqUW0Y=
  file:
  - dist.tar.gz
  - dist.zip
  skip_cleanup: true
  on:
    repo: ufal/public-license-selector
    all_branches: true
    condition: '-n "$TRAVIS_TAG"'
- provider: script
  script: bash ./ci/push_build.sh
  skip_cleanup: true
  on:
    repo: ufal/public-license-selector
    all_branches: true
    condition: '-n "$TRAVIS_TAG" || "$TRAVIS_BRANCH" = "master"'
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=travis
  - secure: moEL3e1aAuPDSMKQBqbZNAp1OFUsu6C+njbIVJyBaYCuwWgAq8l/oDtU1gKGYP7RoNd9+WRHf4RUC/qZVhfrekSeypSW03CdzFsEu5BvlDgNOyVEqL1xck3a7f9QJPOuTibxS9xC1zVzlTtKsOtP3lbwxW/IX5D7PQtxjgvRAqA=

